### ISSUE TITLE
v1.3.0 第2段階の変換でjavaのエラーが発生

### ISSUE THREAD

**Issue by okadatsuneo** [yuuhayashi/citygml-osm#33]
第2段階のmrgファイルの作成処理の途中で、いくつかのファイルで下記のようなエラーが発生し、mrg.osmファイルが作成されません。
----エラー内容----
java.lang.NullPointerException
        at org.locationtech.jts.geom.GeometryOverlay.intersection(GeometryOverlay.java:98)
        at org.locationtech.jts.geom.Geometry.intersection(Geometry.java:1328)
        at osm.surveyor.osm.ElementWay.getIntersectArea(ElementWay.java:274)
        at osm.surveyor.osm.ElementWay.isIntersect(ElementWay.java:294)
        at osm.surveyor.update.OsmUpdater.load(OsmUpdater.java:123)
        at osm.surveyor.update.OsmUpdater$1.accept(OsmUpdater.java:56)
        at osm.surveyor.update.OsmUpdater$1.accept(OsmUpdater.java:45)
        at java.util.Iterator.forEachRemaining(Unknown Source)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
        at osm.surveyor.update.OsmUpdater.main(OsmUpdater.java:45)
----エラー内容----
発生ファイル
飯塚市50303524_bldg_6697_op、50303545_bldg_6697_op、50303554_bldg_6697_op、50303555_bldg_6697_op
などです。

**Comment by okadatsuneo** [comment]
岐阜市のデータでは少し異なるエラーメッセージもありました。
----エラー内容----
java.lang.NullPointerException
        at osm.surveyor.osm.ElementWay.getIntersectArea(ElementWay.java:274)
        at osm.surveyor.osm.ElementWay.isIntersect(ElementWay.java:294)
        at osm.surveyor.update.OsmUpdater.load(OsmUpdater.java:146)
        at osm.surveyor.update.OsmUpdater$1.accept(OsmUpdater.java:56)
        at osm.surveyor.update.OsmUpdater$1.accept(OsmUpdater.java:45)
        at java.util.Iterator.forEachRemaining(Unknown Source)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
        at osm.surveyor.update.OsmUpdater.main(OsmUpdater.java:45)
----エラー内容----
エラー発生ファイル
岐阜市：53360576_bldg_6697_op、53361528_bldg_6697_op、53361618_bldg_6697_op
