### ISSUE TITLE
Windows 10 では エラーが発生

### ISSUE THREAD

**Issue by yuuhayashi** [yuuhayashi/citygml-osm#58]
Windows 10 home , openjdk 11.0.13 では、
`50303524_bldg_6697_op.gml` の3rd で 下記のエラーが発生する。

ただし、Linuxではエラーが発生しないで、正常に処理される。

```
javax.xml.bind.DataBindingException: javax.xml.bind.UnmarshalException 
- with linked exception:                                                                                                
- [com.sun.org.apache.xerces.internal.impl.io.MalformedByteSequenceException: 1▒o▒C▒g▒▒UTF-8▒V▒[▒P▒▒▒X▒̃o▒C▒g1▒▒▒▒▒▒▒ł▒▒B]          at javax.xml.bind.JAXB.unmarshal(JAXB.java:171)                                                                          
- at osm.surveyor.update.OrgFileReadProcessor.process(OrgFileReadProcessor.java:33)                                        
- at org.apache.camel.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:63)
--

`osm.surveyor.update.Test_Issue33.test50303524()` で再現可能。（ただし、Windows のみ）

**Comment by yuuhayashi** [comment]
java 実行時に、`-Dfile.encoding=utf-8` を付ければOK

```
java -Dfile.encoding=utf-8 -jar citygml-osm-jar-with-dependencies.jar 1st
java -Dfile.encoding=utf-8 -jar citygml-osm-jar-with-dependencies.jar 2nd
java -Dfile.encoding=utf-8 -jar citygml-osm-jar-with-dependencies.jar 3rd
```

- v1.3.7-SNAPSHOT にて対応
