### ISSUE TITLE
"2nd" Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by yuuhayashi** [yuuhayashi/citygml-osm#90]
"14100_yokohama-shi_2020_citygml_4_op” で、2nd を実行したら

```
org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[ID-hayashi-TMP455-M-1652999168899-0-416]
	at org.apache.camel.util.ObjectHelper.wrapCamelExecutionException(ObjectHelper.java:1842)
	at org.apache.camel.impl.DefaultExchange.setException(DefaultExchange.java:389)
	at org.apache.camel.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:66)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
	at org.apache.camel.component.direct.DirectProducer.process(DirectProducer.java:76)
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:148)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
	at org.apache.camel.processor.MulticastProcessor.doProcessSequential(MulticastProcessor.java:715)
	at org.apache.camel.processor.MulticastProcessor.doProcessSequential(MulticastProcessor.java:638)
	at org.apache.camel.processor.MulticastProcessor.process(MulticastProcessor.java:248)
	at org.apache.camel.processor.Splitter.process(Splitter.java:129)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
	at org.apache.camel.component.direct.DirectProducer.process(DirectProducer.java:76)
	at org.apache.camel.processor.SharedCamelInternalProcessor.process(SharedCamelInternalProcessor.java:186)
	at org.apache.camel.processor.SharedCamelInternalProcessor.process(SharedCamelInternalProcessor.java:86)
	at org.apache.camel.impl.ProducerCache$1.doInProducer(ProducerCache.java:529)
	at org.apache.camel.impl.ProducerCache$1.doInProducer(ProducerCache.java:494)
	at org.apache.camel.impl.ProducerCache.doInProducer(ProducerCache.java:369)
	at org.apache.camel.impl.ProducerCache.sendExchange(ProducerCache.java:494)
	at org.apache.camel.impl.ProducerCache.send(ProducerCache.java:229)
	at org.apache.camel.impl.DefaultProducerTemplate.send(DefaultProducerTemplate.java:144)
	at org.apache.camel.impl.DefaultProducerTemplate.sendBody(DefaultProducerTemplate.java:161)
	at org.apache.camel.impl.DefaultProducerTemplate.sendBody(DefaultProducerTemplate.java:168)
	at osm.surveyor.osm.camel.OsmDownload.osmDownload(OsmDownload.java:24)
	at osm.surveyor.gml.camel.CitygmlLoad.main(CitygmlLoad.java:23)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
OsmFileProcessor : "53392500_bldg_6697_op.osm"
```

**Comment by yuuhayashi** [comment]
一時的な現象。再実行するとエラーが発生しない。
